name: Pull to DigitalOcean Droplet

on:
  push:
    branches:
      - DebugServer

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'initial deployment'
    outputs:
      should_deploy: ${{ github.event.head_commit.message == 'initial deployment' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
            ssh-private-key: ${{ secrets.DEBUG_SERVER_SSH_TOKEN }}

    - name: Pull latest changes and update dependencies on DigitalOcean Droplet
      run: |
        ssh -o StrictHostKeyChecking=no root@139.59.46.32 << 'EOF'
          cd AddBoost360
          git pull debug DebugServer
          cd apps/server
          pnpm install 
          pm2 restart AddBoost360
        EOF
